# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: cooki
    link: /cooki
  - name: cracker
    submenu:
      - name: lemon
        link: /projects/microbam
      - name: lemon2
        link: /projects/ourlegacy
  - name: cookies
    link: /
  - name: cupcakes
    link: /tags
  - name: browines
    link: /about
  - name: Follow me
